version: "3"

services:
  web:
    build: .
    volumes:
      - .:/service
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8080:8000"
      - "5678:5678"
    env_file:
      - .env
